[options]
addons_path = F:\odoo18\odoo\addons,F:\odoo18\RoongtaERP\
admin_passwd = admin123

db_host = localhost
db_port = 5432
db_user = odoo
db_password = 1234
db_name = roongta_erp

logfile = F:\odoo18\RoongtaERP\roongta.log
http_port = 9900
proxy_mode = False

limit_memory_soft = 268435456
limit_memory_hard = 536870912
limit_time_cpu = 60
limit_time_real = 120
workers = 0

# csv_internal_sep = ,
# data_dir = C:/Users/admin/AppData/Local/Odoo18/data
# data_dir = C:/Users/admin/AppData/Local/Odoo18/data/filestore/rv_enterprise


# python F:\odoo18\odoo\odoo-bin -c odoo.conf
# new database
# python F:\odoo18\odoo\odoo-bin -c odoo.conf -d roongta_erp -i base

# python F:\odoo18\odoo\odoo-bin -c F:\odoo18\RoongtaERP\odoo.conf

